version: "3.9"
services:
  nginx:
    container_name: note-nginx
    image: patomation/note-nginx
    networks:
      - note_network
    ports:
      - 8080:80

  ui:
    container_name: note-ui
    image: patomation/note-ui
    environment:
      - PORT=80
    networks:
      - note_network
    command: npm start

  api:
    image: patomation/note-api
    container_name: note-api
    environment:
      - PORT=80
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - note_network
    command: npm start

networks:
  note_network:
    name: note_network
